name: Deploy to GoDaddy

on:
  push:
    branches:
      - main  # Or the branch you want to deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to GoDaddy
      run: |
        scp -r ./* your_username@yourwebsite.com:/path/to/destination/
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
